formatter: markdown table

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: README.md
  template: |-
    <!-- BEGIN_TF_DOCS -->
    <!-- prettier-ignore-start -->

    {{ .Content }}

    ## Contributing

    Contributions are welcome and appreciated!

    Found an issue or want to request a feature? [Open an issue](TODO)

    Want to fix a bug you found or add some functionality? Fork, clone, commit, push, and PR and we'll check it out.

    If you have any issues or are waiting a long time for a PR to get merged then feel free to ping us at [hello@masterpoint.io](mailto:hello@masterpoint.io).

    ## Built By

    [![Masterpoint Logo](https://i.imgur.com/RDLnuQO.png)](https://masterpoint.io)

    <!-- prettier-ignore-end -->
    <!-- END_TF_DOCS -->

settings:
  anchor: false
  escape: false
  html: false
  lockfile: false
